name: Update games & contexts
on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Pull games (NFL + Soccer)
        run: node scripts/pull_games.mjs
      - name: Build per-game contexts (server-side)
        run: node scripts/build_contexts.mjs
      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/games.json docs/context
          git commit -m "chore: update games & contexts" || echo "no changes"
          git push
